version: "3.9"

services:
  api:
    build: .
    command: python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  streamlit:
    build: .
    command: python -m streamlit run src/app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
